### ISSUE TITLE
How to use graphql template strings

### ISSUE THREAD

**Issue by i-am-the-slime** [jonasbuntinx/gatsby-purescript-example#3]
This is really cool! One thing I struggled with was constructing `graphql"{...}"` strings from within PureScript. Do you know how to do that?

**Comment by jonasbuntinx** [comment]
Sorry for the slow response, I didn't notice until now.

I made this example as a way for me to study GatsbyJS. I haven't gotten very far as I found NextJS more suitable for my needs at the time. As such I have not delved into GraphQL. 

So I'm sorry to say I can't really help you 😞

**Comment by jonasbuntinx** [comment]
I took a little peek into the documentation. So you are talking about this?:

https://www.gatsbyjs.com/docs/page-query/

I think trying to build up a type-safe GraphQL template literal in PureScript would a very big undertaking. 
Maybe best to just leave it as a String.

**Comment by i-am-the-slime** [comment]
Thanks, I didn't see this at the time.
